/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yanming_image_ImageConverter */

#ifndef _Included_com_yanming_image_ImageConverter
#define _Included_com_yanming_image_ImageConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yanming_image_ImageConverter_init
  (JNIEnv *, jobject);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yanming_image_ImageConverter_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    newImageHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_yanming_image_ImageConverter_newImageHandle
  (JNIEnv *, jobject);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    destroyImageHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yanming_image_ImageConverter_destroyImageHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    getHeight
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_yanming_image_ImageConverter_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    getWidth
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_yanming_image_ImageConverter_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    getFormat
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yanming_image_ImageConverter_getFormat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    setFormat
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_setFormat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    setCompressQuality
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_setCompressQuality
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    setBackgroundColor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_setBackgroundColor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    setBorderColor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_setBorderColor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    setDepth
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_setDepth
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    setGravity
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_setGravity
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    readImage
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_readImage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    readImageBlob
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_readImageBlob
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    writeImage
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_writeImage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    strip
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_strip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    crop
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_crop
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    scale
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_scale
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    sample
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_sample
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    sharpen
 * Signature: (JDD)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_sharpen
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    rotate
 * Signature: (JDLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_rotate
  (JNIEnv *, jobject, jlong, jdouble, jstring);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    roll
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_roll
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    extent
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_extent
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_ImageConverter
 * Method:    resize
 * Signature: (JJJDLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_ImageConverter_resize
  (JNIEnv *, jobject, jlong, jlong, jlong, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
