/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yanming_image_Image */

#ifndef _Included_com_yanming_image_Image
#define _Included_com_yanming_image_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yanming_image_Image
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yanming_image_Image_init
  (JNIEnv *, jobject);

/*
 * Class:     com_yanming_image_Image
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yanming_image_Image_destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_yanming_image_Image
 * Method:    newImageHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_yanming_image_Image_newImageHandle
  (JNIEnv *, jobject);

/*
 * Class:     com_yanming_image_Image
 * Method:    destroyImageHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yanming_image_Image_destroyImageHandle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    getHeight
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_yanming_image_Image_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    getWidth
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_yanming_image_Image_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    getFormat
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yanming_image_Image_getFormat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    setFormat
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_setFormat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_Image
 * Method:    setCompressQuality
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_setCompressQuality
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    setBackgroundColor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_setBackgroundColor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_Image
 * Method:    setBorderColor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_setBorderColor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_Image
 * Method:    setDepth
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_setDepth
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    setGravity
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_setGravity
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_Image
 * Method:    readImage
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_readImage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_Image
 * Method:    readImageBlob
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_readImageBlob
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    writeImage
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_writeImage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_yanming_image_Image
 * Method:    strip
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_strip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    crop
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_crop
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    scale
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_scale
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    sample
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_sample
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    sharpen
 * Signature: (JDD)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_sharpen
  (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     com_yanming_image_Image
 * Method:    rotate
 * Signature: (JDLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_rotate
  (JNIEnv *, jobject, jlong, jdouble, jstring);

/*
 * Class:     com_yanming_image_Image
 * Method:    roll
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_roll
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    extent
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_extent
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_yanming_image_Image
 * Method:    resize
 * Signature: (JJJDLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yanming_image_Image_resize
  (JNIEnv *, jobject, jlong, jlong, jlong, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
