/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yanming_image_ImageUtils */

#ifndef _Included_com_yanming_image_ImageUtils
#define _Included_com_yanming_image_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yanming_image_ImageUtils
 * Method:    process
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yanming_image_ImageUtils_process
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
